id: template_chat_flow
name: Template Chat Flow
inputs:
  chat_history:
    type: list
    default: []
    is_chat_input: false
    is_chat_history: true
  query:
    type: string
    default: ""
    is_chat_input: true
outputs:
  reply:
    type: string
    reference: ${stream.output}
    is_chat_output: true
nodes:
- name: formatRewriteIntentInputs
  type: python
  source:
    type: code
    path: formatConversationForIntentRewriting.py
  inputs:
    history: ${inputs.chat_history}
    max_tokens: 100000
    query: ${inputs.query}
  use_variants: false
- name: rewriteIntent
  type: llm
  source:
    type: code
    path: ragcore/prompt_templates/rewriteIntent.jinja2
  inputs:
    deployment_name: gpt-4o-mini-ncsgpt-prod
    temperature: 0.2
    top_p: 0.8
    max_tokens: 4096
    presence_penalty: 0
    frequency_penalty: 0
    conversation: ${formatRewriteIntentInputs.output}
  provider: AzureOpenAI
  connection: ai-aahncsgptprod970548739742_aoai
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
- name: extractSearchIntent
  type: python
  source:
    type: code
    path: extractSearchIntent.py
  inputs:
    intent: ${rewriteIntent.output}
    query: ${inputs.query}
  use_variants: false
- name: checkContent
  type: python
  source:
    type: code
    path: checkContent.py
  inputs:
    query: ${inputs.query}
  use_variants: false
- name: safeResponse
  type: python
  source:
    type: code
    path: safeResponse.py
  inputs:
    content_check_result: ${checkContent.output}
  use_variants: false
- name: querySearchResource
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://ai-aahncsgptprod970548739742.openai.azure.com/
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '1'
        connection:
          id: /subscriptions/7ead1673-f4e7-4808-9bb8-902e34b2a4ce/resourceGroups/rg-ncsgpt-prod/providers/Microsoft.MachineLearningServices/workspaces/aap-ncsgpt-prod/connections/ai-aahncsgptprod970548739742_aoai
        connection_type: workspace_connection
        deployment: text-embedding-3-large-ncsgpt-prod
        dimension: 3072
        kind: open_ai
        model: text-embedding-3-large
        schema_version: '2'
      index:
        api_version: 2024-05-01-preview
        connection:
          id: /subscriptions/7ead1673-f4e7-4808-9bb8-902e34b2a4ce/resourceGroups/rg-ncsgpt-prod/providers/Microsoft.MachineLearningServices/workspaces/aap-ncsgpt-prod/connections/ssncsgptprod
        connection_type: workspace_connection
        endpoint: https://ss-ncsgpt-prod.search.windows.net/
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          metadata: meta_json_string
        index: ssncsgptprod-vector-index-text-embedding-3-large-15
        kind: acs
        semantic_configuration_name: azureml-default
    queries: ${extractSearchIntent.output}
    query_type: Hybrid (vector + keyword)
    top_k: 15
  use_variants: false
- name: chunkDocuments
  type: python
  source:
    type: code
    path: chunkDocuments.py
  inputs:
    data_source: Azure AI Search
    max_tokens: 20000
    queries: ${extractSearchIntent.output}
    query_type: Hybrid (vector + keyword)
    results: ${querySearchResource.output}
    top_k: 15
  use_variants: false
- name: selectChunks
  type: python
  source:
    type: code
    path: filterChunks.py
  inputs:
    min_score: 0.4
    query: ${inputs.query}
    results: ${chunkDocuments.output}
    top_k: 15
  use_variants: false
- name: formatGenerateReplyInputs
  type: python
  source:
    type: code
    path: formatReplyInputs.py
  inputs:
    chunks: ${selectChunks.output}
    content_check_result: ${checkContent.output}
    history: ${inputs.chat_history}
    max_conversation_tokens: 90000
    max_tokens: 100000
    query: ${inputs.query}
  use_variants: false
- name: shouldGenerateReply
  type: python
  source:
    type: code
    path: shouldGenerateReply.py
  inputs:
    query: ${inputs.query}
  use_variants: false
- name: generateReply
  type: llm
  source:
    type: code
    path: ragcore/prompt_templates/generateReply.jinja2
  inputs:
    inputs: ${formatGenerateReplyInputs.output}
    deployment_name: gpt-4.1-ncsgpt-prod
    temperature: 0.2
    top_p: 0.95
    max_tokens: 4096
    presence_penalty: 0
    frequency_penalty: 0
    indomain: ${shouldGenerateReply.output}
  provider: AzureOpenAI
  connection: ai-aahncsgptprod970548739742_aoai
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
- name: merge_responses
  type: python
  source:
    type: code
    path: merge_responses.py
  inputs:
    content_check_result: ${checkContent.output}
    generateReply_output: ${generateReply.output}
    safe_response: ${safeResponse.output}
  use_variants: false
- name: stream
  type: python
  source:
    type: code
    path: stream.py
  inputs:
    paragraph: ${merge_responses.output}
  use_variants: false
node_variants: {}
environment:
  python_requirements_txt: requirements.txt
